name: flutter_widget_lifecycle
description: A new Flutter package can detect when widget is appear or not.
version: 0.0.1
author: tbm98 <tbm98.dev@gmail.com>
homepage: https://github.com/tbm98/flutter_widget_lifecycle
repository: https://github.com/tbm98/flutter_widget_lifecycle
issue_tracker: https://github.com/tbm98/flutter_widget_lifecycle/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: